### ISSUE TITLE
e2e tests don't run on personal linux machines

### ISSUE THREAD

**Issue by tomasmik** [mysteriumnetwork/node#2831]
There are several issues with node e2e tests which occur if you try to run them while you're not the `root` user.

1. Files that containers create are created by the root user:
```sh
tomas@pop-os:~/mysteriumnetwork/node$ ls -l e2e/myst-consumer/keystore/
total 20
-rw-rw-r-- 1 tomas tomas  70 Nov  8 12:33 remember.json
-rw-rw-r-- 1 tomas tomas 489 Nov  8 12:33 UTC--2020-07-31T02-37-15.148642000Z--c4cb9a91b8498776f6f8a0d5a2a23beec9b3cef3
-rw------- 1 root  root  489 Nov 17 15:14 UTC--2020-11-17T13-14-01.202457098Z--d98d868742f6208f9568dd22b3478c9514c9f0ed
-rw------- 1 root  root  489 Nov 17 15:15 UTC--2020-11-17T13-15-16.454095433Z--50e3b5b04869b07efbe92c133462054a0fa58ef9
-rw------- 1 root  root  489 Nov 17 15:15 UTC--2020-11-17T13-15-18.009052934Z--1c469ca8c6d233e13171b22e549961e269093bf9
```
And they're later impossible to access which kills the tests with messages like:
```sh
Building go-runner
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/docker/utils/build.py", line 96, in create_archive
    with open(full_path, 'rb') as f:
PermissionError: ..........
```

This can be fixed by just exporting the user and user group and giving them to compose from env.
Though this is kinda messy and requires some pre-setup because `mage` can't really execute `id -u` or `id -g`.
```yml
  myst-consumer-noop:
    build:
      context: .
      dockerfile: ./bin/docker/alpine-prebuilt/Dockerfile
    user: "${UID:?Please export UID}:${GID:?Please export GID}"
    volumes:
      - ./e2e/myst-consumer/keystore:/var/lib/mysterium-node/testnet2/keystore
```

Or we can use `docker volumes` to store the files

2. Even after this is fixed, tests dont run:
```sh
Error: running "docker-compose -f ./docker-compose.e2e-basic.yml -p node_e2e_basic_test run go-runner /usr/bin/test -test.v -provider.tequilapi-host myst-provider -provider.tequilapi-port=4050 -consumer.tequilapi-port=4050 -consumer.services openvpn,noop,wireguard,hermes2" failed with exit code 2
```
