### ISSUE TITLE
POC - PackageAndroid artifact with NodeUI

### ISSUE THREAD

**Issue by mdomasevicius** [mysteriumnetwork/node#5704]
Check .gitlab-ci (node repo)

```yaml
package:android:
  stage: build
  tags: [go]
  script: go run mage.go -v PackageAndroid
```

- Build Android *.aar with NodeUI enabled
- Test if it is possible to access NodeUI on mobile app
